ARDUINO_DIR  = /usr/share/arduino
ARDUINO_LIBS = Servo Wire Adafruit_BNO055 Adafruit_Unified_Sensor
ARDUINO_SKETCHBOOK = $(realpath .)
BOARD_TAG    = mega2560
ARDUINO_PORT = /dev/ttyACM0

include /usr/share/arduino/Arduino.mk
